### ISSUE TITLE
EOBSMultiplePoints

### ISSUE THREAD

**Issue by khzadeh** [phenology/springtime#76]
I wanted to get E-OBS data from two points using "dataset = EOBSMultiplePoints(points=((target_lon1,target_lat1),(target_lon2,target_lat2)), years=[2020,2022])". However, after loading the data it looks like I get data from four points, i.e., all the possible combinations of lon, lat: (target_lon1,target_lat1), (target_lon1,target_lat2), (target_lon2,target_lat1), (target_lon2,target_lat2)

**Comment by SarahAlidoost** [comment]
@khzadeh I couldn't re-produce the issue. Here are the code samples and output that look fine. (I downloaded the coarse-resolution data to not get memory problems).  
````python
from springtime.datasets.e_obs import EOBSMultiplePoints
dataset = EOBSMultiplePoints(years=[2000, 2002],points=[[5, 50], [5, 55]], grid_resolution="0.25deg") 
dataset.download()

```
Downloading E-OBS variable mean_temperature for 1995-2010 period from https://knmi-ecad-assets-prd.s3.amazonaws.com/ensembles/data/Grid_0.25deg_reg_ensemble/tg_ens_mean_0.25deg_reg_1995-2010_v26.0e.nc to /tmp/data/e-obs/tg_ens_mean_0.25deg_reg_1995-2010_v26.0e.nc
```

df = dataset.load()
print(df)

```
                                 tg
latitude longitude time            
50.125   5.125     2000-01-01  3.50
                   2000-01-02  4.33
                   2000-01-03  4.51
                   2000-01-04  5.09
                   2000-01-05  4.03
...                             ...
55.125   5.125     2002-12-27   NaN
                   2002-12-28   NaN
                   2002-12-29   NaN
                   2002-12-30   NaN
                   2002-12-31   NaN

[4384 rows x 1 columns]
```
````

Can you try this again? If it is possible, first uninstall the current springtime and re-install it again in your activated environment via:
```
pip uninstall springtime
pip install git+https://github.com/phenology/springtime.git
```

If the problem is still there, please copy-paste your code and output here.
